name: CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  python-lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install lint tools
        run: pip install ruff

      - name: Ruff check
        run: ruff check lambda/ glue_etl/ airflow/ scripts/

  dbt-build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: retail_dbt
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dbt (DuckDB adapter)
        run: pip install -r requirements.txt

      - name: dbt seed
        run: dbt seed --profiles-dir ./ci_profiles

      - name: dbt run
        run: dbt run --profiles-dir ./ci_profiles

      - name: dbt test
        run: dbt test --profiles-dir ./ci_profiles
